language: python

python:
  - '3.6'
  
before_install:
  - sudo apt-get update
  - sudo apt-get install -y libcairo2

install:
  - 'pip install pipenv'
  - 'pipenv install .[covers]'

script: python setup.py test
